// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ElementType`.
const ElementType = __t.enum("ElementType", {Wild: __t.unit(),
  Civil: __t.unit(),
  Spritual: __t.unit(),
  Flame: __t.unit(),
  Aqua: __t.unit(),
  Plant: __t.unit(),
  Metal: __t.unit(),
  Earth: __t.unit(),
  Storm: __t.unit(),
  Frost: __t.unit(),
  Toxic: __t.unit(),
  Wind: __t.unit(),
  Stone: __t.unit(),
});

export default ElementType;


