// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  flagKey: __t.string().primaryKey().name("flag_key"),
  flagType: __t.string().name("flag_type"),
  scope: __t.string(),
  category: __t.string(),
  defaultValue: __t.string().name("default_value"),
  description: __t.string(),
});
