// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.2 (commit d53573cc3bd911991a93cfd1143a579e47bb86ef).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import ClientConnectedReducer from "./client_connected_reducer";
export { ClientConnectedReducer };
import ClientDisconnectedReducer from "./client_disconnected_reducer";
export { ClientDisconnectedReducer };
import DebugGetPlayerQuestStateReducer from "./debug_get_player_quest_state_reducer";
export { DebugGetPlayerQuestStateReducer };
import DialogueChoiceReducer from "./dialogue_choice_reducer";
export { DialogueChoiceReducer };
import MovePlayerReducer from "./move_player_reducer";
export { MovePlayerReducer };
import MoveToReducer from "./move_to_reducer";
export { MoveToReducer };
import RequestInteractionReducer from "./request_interaction_reducer";
export { RequestInteractionReducer };
import RequestZoneChangeReducer from "./request_zone_change_reducer";
export { RequestZoneChangeReducer };
import SeedMonDataReducer from "./seed_mon_data_reducer";
export { SeedMonDataReducer };
import SendChatMessageReducer from "./send_chat_message_reducer";
export { SendChatMessageReducer };
import SetDisplayNameReducer from "./set_display_name_reducer";
export { SetDisplayNameReducer };
import TickLoopReducer from "./tick_loop_reducer";
export { TickLoopReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import BlockedTileRow from "./blocked_tile_table";
export { BlockedTileRow };
import ChatMessageRow from "./chat_message_table";
export { ChatMessageRow };
import FlagDefRow from "./flag_def_table";
export { FlagDefRow };
import GameStateRow from "./game_state_table";
export { GameStateRow };
import InteractableDefinitionRow from "./interactable_definition_table";
export { InteractableDefinitionRow };
import InteractableSpawnRow from "./interactable_spawn_table";
export { InteractableSpawnRow };
import MonAbilityCooldownRow from "./mon_ability_cooldown_table";
export { MonAbilityCooldownRow };
import MonEvolutionRuleRow from "./mon_evolution_rule_table";
export { MonEvolutionRuleRow };
import MonFormRow from "./mon_form_table";
export { MonFormRow };
import MonInstanceRow from "./mon_instance_table";
export { MonInstanceRow };
import MoveQueueRow from "./move_queue_table";
export { MoveQueueRow };
import MoveToIntentRow from "./move_to_intent_table";
export { MoveToIntentRow };
import MovementIntentRow from "./movement_intent_table";
export { MovementIntentRow };
import NpcDefinitionRow from "./npc_definition_table";
export { NpcDefinitionRow };
import NpcDialogueActionRow from "./npc_dialogue_action_table";
export { NpcDialogueActionRow };
import NpcSpawnRow from "./npc_spawn_table";
export { NpcSpawnRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import PlayerDialogueEventRow from "./player_dialogue_event_table";
export { PlayerDialogueEventRow };
import PlayerFlagRow from "./player_flag_table";
export { PlayerFlagRow };
import PlayerMonRow from "./player_mon_table";
export { PlayerMonRow };
import PlayerQuestRow from "./player_quest_table";
export { PlayerQuestRow };
import PlayerStateRow from "./player_state_table";
export { PlayerStateRow };
import QuestDebugSnapshotRow from "./quest_debug_snapshot_table";
export { QuestDebugSnapshotRow };
import QuestDefRow from "./quest_def_table";
export { QuestDefRow };
import QuestRewardDefRow from "./quest_reward_def_table";
export { QuestRewardDefRow };
import QuestStepDefRow from "./quest_step_def_table";
export { QuestStepDefRow };
import StarterMonDefRow from "./starter_mon_def_table";
export { StarterMonDefRow };
import TickTimerRow from "./tick_timer_table";
export { TickTimerRow };
import ZoneCollisionRow from "./zone_collision_table";
export { ZoneCollisionRow };
import ZoneSpawnRow from "./zone_spawn_table";
export { ZoneSpawnRow };
import ZoneTransitionRow from "./zone_transition_table";
export { ZoneTransitionRow };

// Import and reexport all types
import BlockedTile from "./blocked_tile_type";
export { BlockedTile };
import ChatMessage from "./chat_message_type";
export { ChatMessage };
import DialogueOption from "./dialogue_option_type";
export { DialogueOption };
import ElementType from "./element_type_type";
export { ElementType };
import FlagDef from "./flag_def_type";
export { FlagDef };
import GameState from "./game_state_type";
export { GameState };
import InteractableDefinition from "./interactable_definition_type";
export { InteractableDefinition };
import InteractableSpawn from "./interactable_spawn_type";
export { InteractableSpawn };
import MonAbilityCooldown from "./mon_ability_cooldown_type";
export { MonAbilityCooldown };
import MonEvolutionRule from "./mon_evolution_rule_type";
export { MonEvolutionRule };
import MonForm from "./mon_form_type";
export { MonForm };
import MonInstance from "./mon_instance_type";
export { MonInstance };
import MoveQueue from "./move_queue_type";
export { MoveQueue };
import MoveToIntent from "./move_to_intent_type";
export { MoveToIntent };
import MovementIntent from "./movement_intent_type";
export { MovementIntent };
import NpcDefinition from "./npc_definition_type";
export { NpcDefinition };
import NpcDialogueAction from "./npc_dialogue_action_type";
export { NpcDialogueAction };
import NpcSpawn from "./npc_spawn_type";
export { NpcSpawn };
import PersonalityType from "./personality_type_type";
export { PersonalityType };
import Player from "./player_type";
export { Player };
import PlayerDialogueEvent from "./player_dialogue_event_type";
export { PlayerDialogueEvent };
import PlayerFlag from "./player_flag_type";
export { PlayerFlag };
import PlayerMon from "./player_mon_type";
export { PlayerMon };
import PlayerQuest from "./player_quest_type";
export { PlayerQuest };
import PlayerState from "./player_state_type";
export { PlayerState };
import QuestDebugSnapshot from "./quest_debug_snapshot_type";
export { QuestDebugSnapshot };
import QuestDef from "./quest_def_type";
export { QuestDef };
import QuestRewardDef from "./quest_reward_def_type";
export { QuestRewardDef };
import QuestStepDef from "./quest_step_def_type";
export { QuestStepDef };
import StarterMonDef from "./starter_mon_def_type";
export { StarterMonDef };
import TickTimer from "./tick_timer_type";
export { TickTimer };
import ZoneCollision from "./zone_collision_type";
export { ZoneCollision };
import ZoneSpawn from "./zone_spawn_type";
export { ZoneSpawn };
import ZoneTransition from "./zone_transition_type";
export { ZoneTransition };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'blocked_tile',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'blocked_tile_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, BlockedTileRow),
  __table({
    name: 'chat_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  __table({
    name: 'flag_def',
    indexes: [
      { name: 'flag_key', algorithm: 'btree', columns: [
        'flagKey',
      ] },
    ],
    constraints: [
      { name: 'flag_def_flag_key_key', constraint: 'unique', columns: ['flagKey'] },
    ],
  }, FlagDefRow),
  __table({
    name: 'game_state',
    indexes: [
      { name: 'singleton', algorithm: 'btree', columns: [
        'singleton',
      ] },
    ],
    constraints: [
      { name: 'game_state_singleton_key', constraint: 'unique', columns: ['singleton'] },
    ],
  }, GameStateRow),
  __table({
    name: 'interactable_definition',
    indexes: [
      { name: 'interactable_def_id', algorithm: 'btree', columns: [
        'interactableDefId',
      ] },
    ],
    constraints: [
      { name: 'interactable_definition_interactable_def_id_key', constraint: 'unique', columns: ['interactableDefId'] },
    ],
  }, InteractableDefinitionRow),
  __table({
    name: 'interactable_spawn',
    indexes: [
      { name: 'interactable_spawn_id', algorithm: 'btree', columns: [
        'interactableSpawnId',
      ] },
    ],
    constraints: [
      { name: 'interactable_spawn_interactable_spawn_id_key', constraint: 'unique', columns: ['interactableSpawnId'] },
    ],
  }, InteractableSpawnRow),
  __table({
    name: 'mon_ability_cooldown',
    indexes: [
      { name: 'player_id', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'mon_ability_cooldown_player_id_key', constraint: 'unique', columns: ['playerId'] },
    ],
  }, MonAbilityCooldownRow),
  __table({
    name: 'mon_evolution_rule',
    indexes: [
      { name: 'evolution_rule_id', algorithm: 'btree', columns: [
        'evolutionRuleId',
      ] },
      { name: 'from_mon_form_id', algorithm: 'btree', columns: [
        'fromMonFormId',
      ] },
    ],
    constraints: [
      { name: 'mon_evolution_rule_evolution_rule_id_key', constraint: 'unique', columns: ['evolutionRuleId'] },
    ],
  }, MonEvolutionRuleRow),
  __table({
    name: 'mon_form',
    indexes: [
      { name: 'mon_form_id', algorithm: 'btree', columns: [
        'monFormId',
      ] },
    ],
    constraints: [
      { name: 'mon_form_mon_form_id_key', constraint: 'unique', columns: ['monFormId'] },
    ],
  }, MonFormRow),
  __table({
    name: 'mon_instance',
    indexes: [
      { name: 'mon_form_id', algorithm: 'btree', columns: [
        'monFormId',
      ] },
      { name: 'mon_instance_id', algorithm: 'btree', columns: [
        'monInstanceId',
      ] },
      { name: 'owner_player_id', algorithm: 'btree', columns: [
        'ownerPlayerId',
      ] },
    ],
    constraints: [
      { name: 'mon_instance_mon_instance_id_key', constraint: 'unique', columns: ['monInstanceId'] },
    ],
  }, MonInstanceRow),
  __table({
    name: 'move_queue',
    indexes: [
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'move_queue_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, MoveQueueRow),
  __table({
    name: 'move_to_intent',
    indexes: [
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'move_to_intent_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, MoveToIntentRow),
  __table({
    name: 'movement_intent',
    indexes: [
      { name: 'intent_id', algorithm: 'btree', columns: [
        'intentId',
      ] },
    ],
    constraints: [
      { name: 'movement_intent_intent_id_key', constraint: 'unique', columns: ['intentId'] },
    ],
  }, MovementIntentRow),
  __table({
    name: 'npc_definition',
    indexes: [
      { name: 'npc_def_id', algorithm: 'btree', columns: [
        'npcDefId',
      ] },
    ],
    constraints: [
      { name: 'npc_definition_npc_def_id_key', constraint: 'unique', columns: ['npcDefId'] },
    ],
  }, NpcDefinitionRow),
  __table({
    name: 'npc_dialogue_action',
    indexes: [
      { name: 'action_id', algorithm: 'btree', columns: [
        'actionId',
      ] },
    ],
    constraints: [
      { name: 'npc_dialogue_action_action_id_key', constraint: 'unique', columns: ['actionId'] },
    ],
  }, NpcDialogueActionRow),
  __table({
    name: 'npc_spawn',
    indexes: [
      { name: 'npc_spawn_id', algorithm: 'btree', columns: [
        'npcSpawnId',
      ] },
    ],
    constraints: [
      { name: 'npc_spawn_npc_spawn_id_key', constraint: 'unique', columns: ['npcSpawnId'] },
    ],
  }, NpcSpawnRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'player_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerRow),
  __table({
    name: 'player_dialogue_event',
    indexes: [
      { name: 'event_id', algorithm: 'btree', columns: [
        'eventId',
      ] },
    ],
    constraints: [
      { name: 'player_dialogue_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, PlayerDialogueEventRow),
  __table({
    name: 'player_flag',
    indexes: [
      { name: 'flag_id', algorithm: 'btree', columns: [
        'flagId',
      ] },
    ],
    constraints: [
      { name: 'player_flag_flag_id_key', constraint: 'unique', columns: ['flagId'] },
    ],
  }, PlayerFlagRow),
  __table({
    name: 'player_mon',
    indexes: [
      { name: 'mon_id', algorithm: 'btree', columns: [
        'monId',
      ] },
    ],
    constraints: [
      { name: 'player_mon_mon_id_key', constraint: 'unique', columns: ['monId'] },
    ],
  }, PlayerMonRow),
  __table({
    name: 'player_quest',
    indexes: [
      { name: 'quest_row_id', algorithm: 'btree', columns: [
        'questRowId',
      ] },
    ],
    constraints: [
      { name: 'player_quest_quest_row_id_key', constraint: 'unique', columns: ['questRowId'] },
    ],
  }, PlayerQuestRow),
  __table({
    name: 'player_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerStateRow),
  __table({
    name: 'quest_debug_snapshot',
    indexes: [
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'quest_debug_snapshot_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, QuestDebugSnapshotRow),
  __table({
    name: 'quest_def',
    indexes: [
      { name: 'quest_id', algorithm: 'btree', columns: [
        'questId',
      ] },
    ],
    constraints: [
      { name: 'quest_def_quest_id_key', constraint: 'unique', columns: ['questId'] },
    ],
  }, QuestDefRow),
  __table({
    name: 'quest_reward_def',
    indexes: [
      { name: 'row_id', algorithm: 'btree', columns: [
        'rowId',
      ] },
    ],
    constraints: [
      { name: 'quest_reward_def_row_id_key', constraint: 'unique', columns: ['rowId'] },
    ],
  }, QuestRewardDefRow),
  __table({
    name: 'quest_step_def',
    indexes: [
      { name: 'row_id', algorithm: 'btree', columns: [
        'rowId',
      ] },
    ],
    constraints: [
      { name: 'quest_step_def_row_id_key', constraint: 'unique', columns: ['rowId'] },
    ],
  }, QuestStepDefRow),
  __table({
    name: 'starter_mon_def',
    indexes: [
      { name: 'starter_id', algorithm: 'btree', columns: [
        'starterId',
      ] },
    ],
    constraints: [
      { name: 'starter_mon_def_starter_id_key', constraint: 'unique', columns: ['starterId'] },
    ],
  }, StarterMonDefRow),
  __table({
    name: 'tick_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'tick_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, TickTimerRow),
  __table({
    name: 'zone_collision',
    indexes: [
      { name: 'zone_id', algorithm: 'btree', columns: [
        'zoneId',
      ] },
    ],
    constraints: [
      { name: 'zone_collision_zone_id_key', constraint: 'unique', columns: ['zoneId'] },
    ],
  }, ZoneCollisionRow),
  __table({
    name: 'zone_spawn',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'zone_spawn_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ZoneSpawnRow),
  __table({
    name: 'zone_transition',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'zone_transition_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ZoneTransitionRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("debug_get_player_quest_state", DebugGetPlayerQuestStateReducer),
  __reducerSchema("dialogue_choice", DialogueChoiceReducer),
  __reducerSchema("move_player", MovePlayerReducer),
  __reducerSchema("move_to", MoveToReducer),
  __reducerSchema("request_interaction", RequestInteractionReducer),
  __reducerSchema("request_zone_change", RequestZoneChangeReducer),
  __reducerSchema("seed_mon_data", SeedMonDataReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("tick_loop", TickLoopReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

