// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  interactableSpawnId: __t.u32().primaryKey().name("interactable_spawn_id"),
  interactableDefId: __t.u32().name("interactable_def_id"),
  zoneId: __t.i32().name("zone_id"),
  tileX: __t.i32().name("tile_x"),
  tileY: __t.i32().name("tile_y"),
});
