// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ElementType from "./element_type_type";


export default __t.object("MonForm", {
  monFormId: __t.i32(),
  dexNumber: __t.i32(),
  code: __t.string(),
  name: __t.string(),
  baseHp: __t.i32(),
  baseSta: __t.i32(),
  baseAtk: __t.i32(),
  baseDef: __t.i32(),
  baseInt: __t.i32(),
  baseSpi: __t.i32(),
  get primaryElement() {
    return ElementType;
  },
  get secondaryElement() {
    return __t.option(ElementType);
  },
  passiveKey: __t.string(),
  activeAbilityKey: __t.string(),
  spriteKey: __t.string(),
  budKey: __t.string(),
  familyTag: __t.option(__t.string()),
  isFinalEvolution: __t.bool(),
});


