// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  evolutionRuleId: __t.i32().primaryKey().name("evolution_rule_id"),
  fromMonFormId: __t.i32().name("from_mon_form_id"),
  toMonFormId: __t.i32().name("to_mon_form_id"),
  conditionKey: __t.option(__t.string()).name("condition_key"),
  requiredValue: __t.option(__t.i64()).name("required_value"),
  minLevel: __t.option(__t.i32()).name("min_level"),
  minBondRank: __t.option(__t.i32()).name("min_bond_rank"),
});
