// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PersonalityType from "./personality_type_type";


export default __t.row({
  monInstanceId: __t.i64().primaryKey().name("mon_instance_id"),
  ownerPlayerId: __t.i64().name("owner_player_id"),
  monFormId: __t.i32().name("mon_form_id"),
  level: __t.i32(),
  experience: __t.i64(),
  bondRank: __t.i32().name("bond_rank"),
  bondExperience: __t.i64().name("bond_experience"),
  get personality() {
    return PersonalityType;
  },
  talentSeed: __t.i64().name("talent_seed"),
  talentHpMod: __t.i32().name("talent_hp_mod"),
  talentStaMod: __t.i32().name("talent_sta_mod"),
  talentAtkMod: __t.i32().name("talent_atk_mod"),
  talentDefMod: __t.i32().name("talent_def_mod"),
  talentIntMod: __t.i32().name("talent_int_mod"),
  talentSpiMod: __t.i32().name("talent_spi_mod"),
  fertilityRemaining: __t.i32().name("fertility_remaining"),
  isInParty: __t.bool().name("is_in_party"),
  partySlot: __t.option(__t.i32()).name("party_slot"),
  createdAt: __t.i64().name("created_at"),
  lastUsedAt: __t.i64().name("last_used_at"),
});
