// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ElementType from "./element_type_type";


export default __t.row({
  monFormId: __t.i32().primaryKey().name("mon_form_id"),
  dexNumber: __t.i32().name("dex_number"),
  code: __t.string(),
  name: __t.string(),
  baseHp: __t.i32().name("base_hp"),
  baseSta: __t.i32().name("base_sta"),
  baseAtk: __t.i32().name("base_atk"),
  baseDef: __t.i32().name("base_def"),
  baseInt: __t.i32().name("base_int"),
  baseSpi: __t.i32().name("base_spi"),
  get primaryElement() {
    return ElementType.name("primary_element");
  },
  get secondaryElement() {
    return __t.option(ElementType).name("secondary_element");
  },
  passiveKey: __t.string().name("passive_key"),
  activeAbilityKey: __t.string().name("active_ability_key"),
  spriteKey: __t.string().name("sprite_key"),
  budKey: __t.string().name("bud_key"),
  familyTag: __t.option(__t.string()).name("family_tag"),
  isFinalEvolution: __t.bool().name("is_final_evolution"),
});
