// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("MonEvolutionRule", {
  evolutionRuleId: __t.i32(),
  fromMonFormId: __t.i32(),
  toMonFormId: __t.i32(),
  conditionKey: __t.option(__t.string()),
  requiredValue: __t.option(__t.i64()),
  minLevel: __t.option(__t.i32()),
  minBondRank: __t.option(__t.i32()),
});


