// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PersonalityType from "./personality_type_type";


export default __t.object("MonInstance", {
  monInstanceId: __t.i64(),
  ownerPlayerId: __t.i64(),
  monFormId: __t.i32(),
  level: __t.i32(),
  experience: __t.i64(),
  bondRank: __t.i32(),
  bondExperience: __t.i64(),
  get personality() {
    return PersonalityType;
  },
  talentSeed: __t.i64(),
  talentHpMod: __t.i32(),
  talentStaMod: __t.i32(),
  talentAtkMod: __t.i32(),
  talentDefMod: __t.i32(),
  talentIntMod: __t.i32(),
  talentSpiMod: __t.i32(),
  fertilityRemaining: __t.i32(),
  isInParty: __t.bool(),
  partySlot: __t.option(__t.i32()),
  createdAt: __t.i64(),
  lastUsedAt: __t.i64(),
});


