// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerIdentity: __t.identity().primaryKey().name("player_identity"),
  queue: __t.string(),
  queueLength: __t.i32().name("queue_length"),
  startTileX: __t.i32().name("start_tile_x"),
  startTileY: __t.i32().name("start_tile_y"),
});
