// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  intentId: __t.u64().primaryKey().name("intent_id"),
  playerIdentity: __t.identity().name("player_identity"),
  dx: __t.i32(),
  dy: __t.i32(),
  clientTick: __t.u64().name("client_tick"),
  receivedAtTick: __t.u64().name("received_at_tick"),
});
