// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("NpcDialogueAction", {
  actionId: __t.u64(),
  eventId: __t.u64(),
  playerIdentity: __t.identity(),
  optionId: __t.u32(),
  npcDefId: __t.i32(),
  actionKind: __t.u8(),
  questId: __t.u32(),
  stepIndex: __t.u16(),
});


