// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcDefId: __t.u32().primaryKey().name("npc_def_id"),
  npcKey: __t.string().name("npc_key"),
  name: __t.string(),
  spriteId: __t.string().name("sprite_id"),
  behaviorId: __t.u32().name("behavior_id"),
  defaultDialogueKey: __t.string().name("default_dialogue_key"),
});
