// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  tileX: __t.i32().name("tile_x"),
  tileY: __t.i32().name("tile_y"),
  facingX: __t.i32().name("facing_x"),
  facingY: __t.i32().name("facing_y"),
  zoneId: __t.i32().name("zone_id"),
  lastMoveTick: __t.u64().name("last_move_tick"),
});
