// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import DialogueOption from "./dialogue_option_type";


export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  playerIdentity: __t.identity().name("player_identity"),
  npcName: __t.string().name("npc_name"),
  text: __t.string(),
  get options() {
    return __t.array(DialogueOption);
  },
});
