// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("PlayerState", {
  identity: __t.identity(),
  tileX: __t.i32(),
  tileY: __t.i32(),
  facingX: __t.i32(),
  facingY: __t.i32(),
  zoneId: __t.i32(),
  lastMoveTick: __t.u64(),
});


