// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questId: __t.u32().primaryKey().name("quest_id"),
  name: __t.string(),
  summary: __t.string(),
  startNpcKey: __t.string().name("start_npc_key"),
  startNpcDefId: __t.i32().name("start_npc_def_id"),
  isRepeatable: __t.bool().name("is_repeatable"),
});
