// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowId: __t.u64().primaryKey().name("row_id"),
  questId: __t.u32().name("quest_id"),
  stepIndex: __t.u16().name("step_index"),
  stepType: __t.string().name("step_type"),
  targetKey: __t.string().name("target_key"),
  targetDefId: __t.i32().name("target_def_id"),
  requiredCount: __t.u32().name("required_count"),
  description: __t.string(),
  choiceLabels: __t.string().name("choice_labels"),
  onCompleteActions: __t.string().name("on_complete_actions"),
});
