// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("QuestDef", {
  questId: __t.u32(),
  name: __t.string(),
  summary: __t.string(),
  startNpcKey: __t.string(),
  startNpcDefId: __t.i32(),
  isRepeatable: __t.bool(),
});


